- hosts: localhost
  connection: local

  vars_files:
    - vars.yaml

  tasks:
    - name: Installing of chaos Dependencies
      shell: sudo apt-get install stress

    - block: 
        - name: Increase IO utilization
          shell: stress --io {{ IO_UTIL }} --timeout {{ CHAOS_DURATION }} 
      when: "{{ IO_CHAOS }}"
